module.exports.states = {
  STARTNEW = 'STARTNEW',
  PLAYING = 'PLAYING',
  DEALING = 'DEALING',
  STOPPED = 'STOPPED',
  SPLIT = 'SPLIT',
  SPLITSECONDHAND = 'SPLITSECONDHAND',
  DEALSPLIT = 'DEALSPLIT',
  PLAYERBUST = 'PLAYERBUST',
  DEALERBUST = 'DEALERBUST',
  PLAYERWINS = 'PLAYERWINS',
  DEALERWINS = 'DEALERWINS'
};
